### ISSUE TITLE
'notepad.exe' shows old content, while 'cat' shows correct content.

### ISSUE THREAD

**Issue by gamlerhart** [lundman/ZFSin#14]
Reproduce:
   - Open file with notepad.exe (or right click edit).
   - Edit it, save.
   - Reopen it: It shows old content.
   - However 'cat file' (powershell) shows correct content.

Given that 'cat' and notepad give different content: Looks like it's served from different cache?
Looks like one is served via ZFS, one from Windows cache.

More investigations will follow.

**Comment by gamlerhart** [comment]
Confirmed: The 'stale' read happens with memory mapped file. If reopening the memory mapped file, it still sees the old content.

Not sure where the memory mapping is handled? I don't see a dispatch call for that. Or maybe that is part of the problem.

When the memory mapping opens / closes, I see a 'CREATE' & 'QUERY_INFORMATION' call, like in the log below.
Nothing which screams 'memory-mapping'.

Anyway. Will continue to investigate.

`dispatcher: enter: major 0: minor 0: IRP_MJ_CREATE
  fsDispatcher: enter: major 0: minor 0: IRP_MJ_CREATE fsDeviceObject
IRP_MJ_CREATE: FileObject FFFF90099E2D7750 related 0000000000000000 name '\b8a085b6-ce72-46db-90dd-23919ec45c8b' flags 0x0
zfs_vnop_lookup: enter
+zget 4
+zget 34
dispatcher: exit: 0x0 OK Information 0x1
dispatcher: enter: major 5: minor 0: IRP_MJ_QUERY_INFORMATION
  fsDispatcher: enter: major 5: minor 0: IRP_MJ_QUERY_INFORMATION fsDeviceObject
* query_information: FileNetworkOpenInformation
   file_network_open_information
dispatcher: exit: 0x0 OK Information 0x38
dispatcher: enter: major 18: minor 0: IRP_MJ_CLEANUP
  fsDispatcher: enter: major 18: minor 0: IRP_MJ_CLEANUP fsDeviceObject
IRP_MJ_CLEANUP: iocount 0 usecount 1
dispatcher: exit: 0x0 OK Information 0x0
dispatcher: enter: major 2: minor 0: IRP_MJ_CLOSE
  fsDispatcher: enter: major 2: minor 0: IRP_MJ_CLOSE fsDeviceObject
IRP_MJ_CLOSE: iocount 0 usecount 0
dispatcher: exit: 0x0 OK Information 0x0`

**Comment by lundman** [comment]
All you have to do, is unmount and remount the fs after you save with notepad.exe!

Usually in these cases, once you get called to write, you should also either update the cache-memory with the writes, or flush the cache. The other openzfs ports update the cache memory on write.
