### ISSUE TITLE
Native encryption support

### ISSUE THREAD

**Issue by mcilloni** [lundman/ZFSin#8]
Thanks a lot to the author of this awesome project, being able to natively access ZFS pools from Windows would be awesome. Do you also plan to add support for native encryption to this driver or it's something not really feasible do accomplish?

**Comment by lundman** [comment]
It just needs https://github.com/openzfsonosx/zfs/commit/4644f6879971c34a47d4f8e8417c760640716125 cherry-picked in, and the 2 commits of fixes.  Updating it since I started (Feb 2017) has not been my priority so far, it's not exactly ready for general use after all

**Comment by mailinglists35** [comment]
> it's not exactly ready for general use after all

yes but people want it as it is

**Comment by lundman** [comment]
4b6de000d1f20d7d0928b27d145bc473d7a071d0
